# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/f62/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),f62)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-E625F,41b1479c1ac5d7984c1376c1ffa50c3ca4f0d8fe)
$(call add-radio-file-sha1-checked,radio/cm.bin_SM-M625F,bf30dd43ac0174d300621415fc4134555252a72c)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-E625F,f3968c6b9f345900eb93c2a3f04e687a04d84403)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-M625F,9a3084e9f9233f5619e909ce63040095253f42cd)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-E625F,2666d52e86fa45ff08198e69b010d2958a62c91f)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-M625F,c52e1bc73b63538b1f7c94dc53e7927be6ab4123)
$(call add-radio-file-sha1-checked,radio/models,7a88be8b138bbefc5b015fac6c86cf301c7ce9f1)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-E625F,7e7e368d23316f01951e18adca6e50c46a1e0fac)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-M625F,bb4a819961b3658ae97719dabab36c28a1547766)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-E625F,1e9ba1570bbed4d0409906029b3f264163c09e71)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-M625F,1f97420d4972f42a82613a972b477d94fb8a71e5)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-E625F,88bff3b6bf35e12fbc0c6491dd35dde7b0d1b41e)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-M625F,72c9005bf3854884405398d88042040990eb3213)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-E625F,089091baa27b3a3dff6a6b01aa30c7eafab11d01)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-M625F,6f577391198797f0a242d118eea30ee3508fac13)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-E625F,51aa14748f42834aec7844ae584a0af91ce38957)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-M625F,282d48df29d67740ba33a08e30399aa5f58aefb3)
$(call add-radio-file-sha1-checked,radio/version_SM-E625F,4a5dd3e96377a412c2c7623c4cdfee6d7f4ac4d2)
$(call add-radio-file-sha1-checked,radio/version_SM-M625F,1923c1ee9b1737d251c498f1383164b588253fc4)

endif
