# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/f62/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),f62)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-E625F,9c225c2213a875556d13705389f107ca88d36c96)
$(call add-radio-file-sha1-checked,radio/cm.bin_SM-M625F,6e5bb40b1975cc9834bbd7cac62684017437d6cc)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-E625F,40d4cc3332b7be0c58633b9e3d5083e6e40253a3)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-M625F,491cf44b9a2c272e47051516d50c57c168acc93d)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-E625F,683c0bec117692e67bb4a97db13ea0807cb7c175)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-M625F,09ce1492719f1bcbca29565c11dba44811a19f2f)
$(call add-radio-file-sha1-checked,radio/models,7a88be8b138bbefc5b015fac6c86cf301c7ce9f1)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-E625F,1b167918238c549713acd441649c4be33808515d)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-M625F,94d73ca043798517187a2e5c433fc848c7bd07c9)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-E625F,14fd07dd18eec852bb062d5341be7cec0d2ad467)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-M625F,e741a86205bfcc1bc27b78540f4478a43ed05a5c)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-E625F,a90e8cfdd8041cd81db90bde8f5dc02cf0677129)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-M625F,7e4c9a6b14bbf90bfbce57323817f3d7f9376544)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-E625F,ca7025ea0b950cbe286ad568e60304ef085e0901)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-M625F,15e5a9b1b83a97151855ef4cf77e5588bd1dd73e)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-E625F,08b4c2c2b6448f7c5d791a0da8ae4f69bf6202c5)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-M625F,801aba2d766e272798035ac3682e125a921ef546)
$(call add-radio-file-sha1-checked,radio/version_SM-E625F,ceec7e32f5a1658e89f80b03259d918af4d91a62)
$(call add-radio-file-sha1-checked,radio/version_SM-M625F,415c3d459add518b31e4cc520f157f3b91833f7f)

endif
